((default)
    (doom . ((user-emacs-directory . "~/.local/share/emacsen/doom")
                  (custom-file . "~/.config/emacsen/doom/custom.el")
                  (server-name . "doom")
                  (doom-user-dir . "~/.config/emacsen/doom")
                  (doom-cache-dir :path "~/.cache/emacsen/doom")
		  (doom-data-dir :path "~/.local/share/emacsen/doom")
		  (doom-state-dir :path "~/.local/state/emacsen/doom")))
    (prelude . ((user-emacs-directory . "~/.local/share/emacsen/prelude")
                     (server-name . "prelude")
                     ("PRELUDE_CONFIG_HOME" . "~/.config/emacsen/prelude")))
    (centaur . ((user-emacs-directory . "~/.local/share/emacsen/centaur")
                     (server-name . "centaur")))
    (spacemacs . ((user-emacs-directory . "~/.local/share/emacsen/spacemacs")
                       (server-name . "spacemacs"))))
